### ISSUE TITLE
Hyperparameters setting?

### ISSUE THREAD

**Issue by ztb-35** [DC-research/TEMPO#1]
Dear authors:

Thanks for your great work and simple but efficient code. But I didn't find your hyperparameters setting in your code or paper.
Could you give me a list of hyperparameters setting for gpt2? I am really interested in your brilliant work and want to reproduce it.

Thanks!

**Comment by idevede** [comment]
Dear ztb-35,

Thank you for your kind words and interest in our work! 😁

The hyperparameter settings are located in the ‘scripts’ folder. FYI, we are currently working on updating the demo for more applications, which should be available soon.
