### ISSUE TITLE
UnboundLocalError: local variable 'seq_trend' referenced before assignment AFTER training for 1 epoch by train_TEMPO.py

### ISSUE THREAD

**Issue by Lanxin1011** [DC-research/TEMPO#10]
Dear Authors:
Thanks for you brilliant work! I encountered an error when running the train_TEMPO.py script, could you please take a look on how to solve the problem? Thanks a lot! 

Here is the error info:
`100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 1757/1757 [08:11<00:00,  3.5100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 1757/1757 [08:11<00:00,  3.58it/s]
Epoch: 1 cost time: 491.01318168640137
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "train_TEMPO.py", line 342, in <module>
    vali_loss = vali(model, vali_data, vali_loader, criterion, args, device, ii)
  File "/mnt/workspace/TEMPO/utils/tools.py", line 352, in vali
    seq_trend = seq_trend.float().to(device)
UnboundLocalError: local variable 'seq_trend' referenced before assignment`

**Comment by Lanxin1011** [comment]
I modified line 343 as `batch_x, batch_y, batch_x_mark, batch_y_mark, seq_trend, seq_seasonal, seq_resid = data[0], data[1], data[2], data[3], data[4], data[5], data[6]` , and the error disappeared. Could you please tell me if the modification I've made is correct?

Best regards

**Comment by idevede** [comment]
Hi Lanxin1011,

Thank you for your interest in our work and for actively engaging with the experiments. You are correct regarding your suggested changes. I intended to add code adaptability for different dataloaders but inadvertently omitted this code. Let me fix it quickly.

Best
