### ISSUE TITLE
Hello, when I run the ’train_tempo’ file, I always encounter the problem shown in the figure. Could you please give me some suggestions to fix this problem?

### ISSUE THREAD

**Issue by Lining160** [DC-research/TEMPO#13]
![{AD34E1DA-A7D0-4B74-824E-EE741A0A6A32}](https://github.com/user-attachments/assets/cf421c6f-5c5f-468c-9ac0-3239b8833c6d)

In case you can't see the error picture, I wrote the problem here.
"   0%|                                                   | 0/294 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/ubuntu/WorkSpace/LN/TEMPO-main/TEMPO-main/train_TEMPO.py", line 316, in <module>
    outputs, loss_local = model(batch_x,args,device) #+ model(seq_seasonal, ii) + model(seq_resid, ii)
  File "/home/ubuntu/miniconda3/envs/mypytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() takes 3 positional arguments but 4 were given
"

**Comment by idevede** [comment]
Hi Lining,

Thanks for your interest in our TEMPO work! Could you please try to download our new version and also try setting the parameters using the demo from ‘scripts/monash.sh’. I’ve tried the new version, and it doesn’t show the problem, so I think the issue might be that you haven’t specified the model to 'TEMPO'.

Best,

Authors
